name: AI local model CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform -chdir=provider init

      - name: Apply Terraform configuration
        run: terraform -chdir=provider apply -auto-approve

      - name: Get VM IP Address
        id: get_ip
        run: |
          VM_IP=$(terraform -chdir=provider output --raw vm_public_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

      - name: Note
        run: |
          echo "Cloud-init will run deploy-on-cloud.sh on the VM at first boot. No SSH deploy step is executed from this workflow."
