name: AI local model CD Pipeline

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    env:
      # Set the working directory for all Terraform commands
      TF_WORKING_DIR: cloud/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TF_VAR_client_secret }} # Use a service principal with contributor role on the resource group

      - name: Initialize Terraform
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Apply Terraform configuration
        id: terraform_apply
        run: |
          terraform -chdir=${{ env.TF_WORKING_DIR }} apply \
            -var="openai_key=${{ secrets.OPENAI_KEY }}" \
            -auto-approve
