name: Destroy Infrastructure

on:
    workflow_dispatch:

jobs:
    Destroy:
        name: Destroy Azure Resources
        runs-on: ubuntu-latest
        env:
            TF_WORKING_DIR: cloud/terraform

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.7

            - name: Login to Azure using Service Principal
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Initialize Terraform
              run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

            - name: Destroy Terraform-managed infrastructure
              run: |
                  terraform -chdir=${{ env.TF_WORKING_DIR }} destroy -auto-approve

            - name: Destruction Complete
              run: echo "✅ All Terraform-managed resources have been destroyed."
