name: AI local model CD Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write # ✅ Needed for OIDC authentication
  contents: read # ✅ Required to checkout the repo

jobs:
  Deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: cloud/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          auth-type: oidc
          client-id: ${{ secrets.TF_VAR_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_VAR_TENANT_ID }}
          subscription-id: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}

      - name: Initialize Terraform
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Apply Terraform configuration
        run: |
          terraform -chdir=${{ env.TF_WORKING_DIR }} apply \
            -var="openai_key=${{ secrets.OPENAI_KEY }}" \
            -auto-approve
