name: AI local model CI Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Test_and_Build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort

      - name: Check Python syntax
        run: |
          echo "🔍 Checking Python syntax..."
          find . -name "*.py" -not -path "./venv/*" | while read file; do
            echo "Checking $file..."
            python -m py_compile "$file" || exit 1
          done
          echo "✅ All Python files have valid syntax"

      - name: Lint and format checks
        run: |
          flake8 app.py --max-line-length=100 --ignore=E203,W503 || echo "⚠️ flake8 warnings"
          black --check app.py || echo "⚠️ Formatting issues"

      - name: Build Docker image
        run: |
          docker build -t crooper/ai-model:latest .
          echo "✅ Docker image built"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push crooper/ai-model:latest
          echo "✅ Docker image pushed"
